version: "3.9"
   
services:
  mongo:
    image: mongo
    restart: always
    command: --quiet
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_PORT: ${MONGO_PORT}
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
  redis:
    image: "redis:6.2.4"
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
  node:
    image: "node:16.3.0"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      - ./:/home/node/app
    ports:
      - "${PORT}:${PORT}"
    command: "npm start"
    depends_on:
      - mongo
      - redis